### ISSUE TITLE
on python3.6 is error

### ISSUE THREAD

**Issue by cncg51** [vcodeclub/graphic-verification-code#1]
python3.6 运行报错
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gvcode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python36\lib\site-packages\gvcode\__init__.py", line 3, in <module>
    from gvcode.main import base64, generate
  File "D:\Python36\lib\site-packages\gvcode\main.py", line 6, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

**Comment by Brightcells** [comment]
谢谢反馈，已经处理，麻烦再试一下

https://github.com/vcodeclub/graphic-verification-code/commit/7d0db07cd8943144fae7f93c60ccde983a15f4e6
